### ISSUE TITLE
支付宝链接

### ISSUE THREAD

**Issue by colay616** [lijiayan2015/ExpandWebView#1]
请问支付宝HTTPS://QR.ALIPAY.COM/FKX01765CJRLKFJA53GW95这个链接怎么生成的？

**Comment by lijiayan2015** [comment]
打开支付宝收款码,然后用微信扫一扫,就可以看到这个链接了^_^

**Comment by lijiayan2015** [comment]
@colay616 打开支付宝收款码,然后用微信扫一扫就可以看到了^_^
